version: '3'
services:
  frontend:
    build:
      context: ./webClient
    ports:
      - "5173:5173"

  backend:
    build:
      context: ./flask_server
    ports:
      - "8000:8000"
