name: Run Tests

 

on: 
    pull_request:
        branches: [ main ]
    workflow_dispatch:

jobs:
    jest-test:
        runs-on: ${{ matrix.os }}

 

        strategy:
            matrix:
                os: [windows-latest,ubuntu-latest,macos-latest]
                node-version: [14.x, 16.x, 18.x, 20.x]

 

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: yarn install
              run: |
                  yarn install
            - name: test
              run: |
                  yarn test --findRelatedTests webClient/src/tests/unit/