name: Playwright Tests
on:
  push:
    branches: [ main, master,Devops ]
  pull_request:
    branches: [ main, master,Devops ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: List files in current directory
      run: ls
    - name: pwd
      run: pwd
    - name: Navigate to project directory
      run : cd ./Client
    - name: pwd
      run: pwd
    - name: List files in Client directory
      run: ls
    - name: Install dependencies
      run: yarn
    - name: Clear Playwright cache
      run: yarn playwright clear-cache
    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps
    - name: Run Playwright tests
      run: yarn playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
